import { Platform, StyleSheet } from 'react-native';

export function makeStyles(theme) {
  return StyleSheet.create({
    safeArea: { flex: 1, backgroundColor: theme.background },
    screen: { flex: 1, backgroundColor: theme.background, padding: 18, maxWidth: 980, width: '100%', alignSelf: 'center' },
    centered: { flex: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: theme.background },
    scrollContent: { paddingBottom: 28 },
    header: { marginBottom: 18, gap: 8 },
    title: { color: theme.text, fontSize: 30, fontWeight: '800' },
    subtitle: { color: theme.muted, fontSize: 15, lineHeight: 22 },
    card: { backgroundColor: theme.surface, borderColor: theme.border, borderWidth: 1, borderRadius: 8, padding: 16, marginBottom: 12, gap: 10 },
    row: { flexDirection: 'row', alignItems: 'center', gap: 10 },
    wrapRow: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', gap: 10 },
    between: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10, flexWrap: 'wrap' },
    input: {
      minHeight: 46,
      borderColor: theme.border,
      borderWidth: 1,
      borderRadius: 8,
      paddingHorizontal: 12,
      color: theme.text,
      backgroundColor: theme.surface,
      outlineStyle: Platform.OS === 'web' ? 'none' : undefined,
    },
    textArea: { minHeight: 86, paddingTop: 12, textAlignVertical: 'top' },
    button: { minHeight: 46, borderRadius: 8, paddingHorizontal: 16, alignItems: 'center', justifyContent: 'center', backgroundColor: theme.primary },
    buttonText: { color: theme.primaryText, fontWeight: '700', fontSize: 15 },
    ghostButton: {
      minHeight: 42,
      borderRadius: 8,
      paddingHorizontal: 14,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.surfaceAlt,
      borderWidth: 1,
      borderColor: theme.border,
    },
    ghostText: { color: theme.text, fontWeight: '700' },
    dangerText: { color: theme.danger, fontWeight: '700' },
    smallText: { color: theme.muted, fontSize: 13 },
    error: { color: theme.danger, fontWeight: '700' },
    statGrid: { flexDirection: 'row', gap: 10, flexWrap: 'wrap' },
    statCard: { flexGrow: 1, minWidth: 145, backgroundColor: theme.surface, borderRadius: 8, padding: 16, borderColor: theme.border, borderWidth: 1 },
    statNumber: { color: theme.text, fontSize: 28, fontWeight: '800' },
    calendarGrid: { flexDirection: 'row', flexWrap: 'wrap', borderTopWidth: 1, borderLeftWidth: 1, borderColor: theme.border },
    weekdayCell: { width: `${100 / 7}%`, paddingVertical: 8, alignItems: 'center' },
    weekdayText: { color: theme.muted, fontWeight: '700', fontSize: 12 },
    dayCell: { width: `${100 / 7}%`, minHeight: 76, borderRightWidth: 1, borderBottomWidth: 1, borderColor: theme.border, padding: 6, backgroundColor: theme.surface, gap: 6 },
    emptyDay: { backgroundColor: theme.background },
    todayCell: { backgroundColor: theme.today },
    selectedDay: { borderColor: theme.primary, borderWidth: 2 },
    dayNumber: { color: theme.text, fontWeight: '800' },
    dots: { flexDirection: 'row', flexWrap: 'wrap', gap: 3 },
    dot: { width: 7, height: 7, borderRadius: 7 },
    taskTitle: { color: theme.text, fontSize: 16, fontWeight: '800' },
    taskMeta: { color: theme.muted, fontSize: 13 },
    colorSwatch: { width: 28, height: 28, borderRadius: 6, borderWidth: 2, borderColor: theme.border },
    colorSwatchSelected: { borderColor: theme.text },
  });
}
