#!/bin/bash
# 🚀 GUIA RÁPIDO - EXECUTAR TESTES PLAYWRIGHT
# Login-Att | Maio 2026

echo "═══════════════════════════════════════════════════════════"
echo "  📋 PLANO DE TESTES - APLICAÇÃO LOGIN-ATT"
echo "═══════════════════════════════════════════════════════════"
echo ""

# Cores para output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}✅ PASSO 1: VERIFICAR PRÉ-REQUISITOS${NC}"
echo ""
echo "Certifique-se de que você tem 3 TERMINAIS ABERTOS:"
echo ""
echo -e "${YELLOW}Terminal 1: EXPO SERVER${NC}"
echo "  $ npm start"
echo "  ✓ Aguarde aparecer opções de plataforma"
echo ""
echo -e "${YELLOW}Terminal 2: JSON SERVER${NC}"
echo "  $ npx json-server --watch data/data/bancoDeDados.json --port 3000 --host 10.125.214.183"
echo "  ✓ Aguarde mensagem: 'JSON Server is running'"
echo ""
echo -e "${YELLOW}Terminal 3: TESTES PLAYWRIGHT${NC}"
echo "  $ Rode os comandos abaixo neste terminal"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo ""

echo -e "${BLUE}✅ PASSO 2: CLONAR OU COPIAR DADOS DE TESTE${NC}"
echo ""
echo "Usuários disponíveis no data/bancoDeDados.json:"
echo ""
echo "  👤 Admin:"
echo "     Usuário: ${GREEN}admin${NC}"
echo "     Senha:   ${GREEN}123${NC}"
echo ""
echo "  👤 Maria:"
echo "     Usuário: ${GREEN}Maria${NC}"
echo "     Senha:   ${GREEN}456${NC}"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo ""

echo -e "${BLUE}✅ PASSO 3: EXECUTAR TESTES${NC}"
echo ""
echo -e "${GREEN}🎯 EXECUTAR TODOS OS TESTES:${NC}"
echo "  $ npx playwright test tests/login-tarefas.spec.ts"
echo ""
echo -e "${GREEN}🎯 EXECUTAR APENAS TESTES DE LOGIN:${NC}"
echo "  $ npx playwright test tests/login-tarefas.spec.ts -g \"Testes de Login\""
echo ""
echo -e "${GREEN}🎯 EXECUTAR APENAS TESTES DE TAREFAS:${NC}"
echo "  $ npx playwright test tests/login-tarefas.spec.ts -g \"Testes de Gerenciamento de Tarefas\""
echo ""
echo -e "${GREEN}🎯 EXECUTAR APENAS TESTES DE NAVEGAÇÃO:${NC}"
echo "  $ npx playwright test tests/login-tarefas.spec.ts -g \"Testes de Navegação\""
echo ""
echo -e "${GREEN}🎯 EXECUTAR APENAS TESTES DE PERFORMANCE:${NC}"
echo "  $ npx playwright test tests/login-tarefas.spec.ts -g \"Testes de Performance\""
echo ""
echo "═══════════════════════════════════════════════════════════"
echo ""

echo -e "${BLUE}✅ PASSO 4: OPÇÕES AVANÇADAS${NC}"
echo ""
echo -e "${GREEN}🔍 MODO DEBUG (Interativo):${NC}"
echo "  $ npx playwright test tests/login-tarefas.spec.ts --debug"
echo ""
echo -e "${GREEN}👀 MODO HEADED (Ver o browser executando):${NC}"
echo "  $ npx playwright test tests/login-tarefas.spec.ts --headed"
echo ""
echo -e "${GREEN}🔄 MODO WATCH (Reexecuta ao salvar arquivo):${NC}"
echo "  $ npx playwright test tests/login-tarefas.spec.ts --watch"
echo ""
echo -e "${GREEN}📊 VER RELATÓRIO HTML:${NC}"
echo "  $ npx playwright show-report"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo ""

echo -e "${BLUE}✅ PASSO 5: CENÁRIOS ESPECÍFICOS${NC}"
echo ""
echo "Você pode testar cenários específicos:"
echo ""
echo -e "${GREEN}1️⃣ ENTRAR COM USUÁRIO INVÁLIDO:${NC}"
echo "  $ npx playwright test tests/login-tarefas.spec.ts -g \"Falha ao entrar com usuário inválido\""
echo "  ✓ Testa rejeição de credenciais erradas"
echo ""
echo -e "${GREEN}2️⃣ ADICIONAR NOVA TAREFA:${NC}"
echo "  $ npx playwright test tests/login-tarefas.spec.ts -g \"Adicionar nova tarefa com sucesso\""
echo "  ✓ Cria tarefa e valida na lista"
echo ""
echo -e "${GREEN}3️⃣ EDITAR TAREFA EXISTENTE:${NC}"
echo "  $ npx playwright test tests/login-tarefas.spec.ts -g \"Editar tarefa existente\""
echo "  ✓ Abre modal, edita e salva alterações"
echo ""
echo -e "${GREEN}4️⃣ MARCAR TAREFA COMO CONCLUÍDA:${NC}"
echo "  $ npx playwright test tests/login-tarefas.spec.ts -g \"Marcar tarefa como concluída\""
echo "  ✓ Alterna status visual e na API"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo ""

echo -e "${YELLOW}⚠️  TROUBLESHOOTING${NC}"
echo ""
echo -e "${RED}❌ ERRO: Timeout${NC}"
echo "   → Verificar se Expo/JSON Server estão rodando"
echo "   → Verificar URL correta em playwright tests"
echo ""
echo -e "${RED}❌ ERRO: Elemento não encontrado${NC}"
echo "   → Usar: npx playwright test --debug"
echo "   → Ajustar seletores CSS/XPath"
echo ""
echo -e "${RED}❌ ERRO: Falha de conexão${NC}"
echo "   → Verificar se IP 10.125.214.183 está correto"
echo "   → Ping no servidor: ping 10.125.214.183"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo ""

echo -e "${GREEN}✨ TUDO PRONTO!${NC}"
echo ""
echo "Próximos passos:"
echo "1. Abra 3 terminais"
echo "2. Terminal 1: npm start"
echo "3. Terminal 2: npx json-server --watch data/data/bancoDeDados.json --port 3000"
echo "4. Terminal 3: npx playwright test tests/login-tarefas.spec.ts"
echo ""
echo "Boa sorte! 🎉"
echo ""
echo "═══════════════════════════════════════════════════════════"
